version: "2.3"

services:
  flexwire:
    build:
      dockerfile: Dockerfile
      context: .
    image: flexwire:latest
    container_name: flexwire
    volumes:
      - static_volume:/flexwire/static
      - media_volume:/flexwire/media
    env_file:
      - .env
    command: >
      bash -c "python3 manage.py collectstatic --noinput && python3 manage.py migrate  && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
  nginx:
    container_name: flexwire-nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/flexwire/static
      - media_volume:/flexwire/media
    network_mode: host
    depends_on:
      - flexwire
    restart: unless-stopped


volumes:
  static_volume:
  media_volume:
