# Generated by Django 3.2.17 on 2023-04-15 21:09

from django.db import migrations
from django.db import models
import django.db.models.deletion

import feedback.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_on',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='date of writing'
                    ),
                ),
                (
                    'mail',
                    models.EmailField(
                        default='user_mail@example.com',
                        help_text='Write your email',
                        max_length=254,
                        verbose_name='mail',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('got', 'Got'),
                            ('in progress', 'In progress'),
                            ('answered', 'Answered'),
                        ],
                        default='got',
                        help_text='Choose application status',
                        max_length=11,
                        verbose_name='status',
                    ),
                ),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='FeedbackText',
            fields=[
                (
                    'feedback',
                    models.OneToOneField(
                        help_text='Write your feedback',
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to='feedback.feedback',
                        verbose_name='text',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        blank=True,
                        help_text='Write feedback to our site',
                        null=True,
                        verbose_name='feedback',
                    ),
                ),
            ],
            options={
                'verbose_name': 'feedback text',
                'verbose_name_plural': 'feedback texts',
            },
        ),
        migrations.CreateModel(
            name='FeedbackFiles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'files',
                    models.FileField(
                        default=None,
                        help_text='Load additional files',
                        null=True,
                        upload_to=feedback.models.FeedbackFiles.saving_path,
                        verbose_name='files',
                    ),
                ),
                (
                    'feedback',
                    models.ForeignKey(
                        default=None,
                        help_text='Load files',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='feedback.feedback',
                        verbose_name='files',
                    ),
                ),
            ],
            options={
                'verbose_name': 'feedback file',
                'verbose_name_plural': 'feedback files',
            },
        ),
    ]
